use eshop;

INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (1,'FOODS','apple.png',17810,'사과 4개 1kg');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (2,'ELECTRONICS','hp-laptop.png',779000,'HP 노트북');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (3,'FASHION','sneakers.png',24800,'운동화');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (4,'KITCHEN','utensils.png',21900,'수저 포크 세트');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (5,'FOODS','rice.png',30690,'오뚜기밥 30개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (6,'FOODS','spicy-ramyeon.png',31780,'불닭볶음면 40개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (7,'ELECTRONICS','iphone.png',1100000,'아이폰 13');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (8,'FASHION','dress1.png',28910,'후드 원피스');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (9,'BEAUTY','perfume1.png',56500,'향수 30ml 1개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (10,'FOODS','chicken1.png',14620,'닭 날개 윙 1kg 1개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (11,'KITCHEN','frying-pan.png',31560,'후라이팬');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (12,'BATHROOM','toothbrush.png',12670,'칫솔 20개 1세트');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (13,'FOODS','cake1.png',24860,'치즈케익');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (14,'ELECTRONICS','nintendo-switch.png',414120,'닌텐도 스위치');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (15,'BATHROOM','toothpaste.png',36860,'치약 4개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (16,'FOODS','spam.png',34000,'스팸 10개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (17,'FOODS','curry.png',28600,'카레 8개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (18,'KITCHEN','lunchbox.png',27560,'보온도시락');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (19,'FASHION','t-shirt.png',19150,'면 티셔츠');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (20,'FOODS','cup-ramyeon1.png',12800,'컵 진라면 12개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (21,'ELECTRONICS','refrigerator.png',599000,'냉장고');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (22,'BATHROOM','bathroom-cleaner.png',13130,'욕실 클리너');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (23,'BEAUTY','water-cream.png',21220,'수분 진정 크림');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (24,'FASHION','blue-jeans.png',11900,'청바지');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (25,'KITCHEN','storage-container.png',21100,'밀폐용기 8칸 3.8L');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (26,'ELECTRONICS','tv.png',229900,'LED TV');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (27,'FOODS','cup-noodle.png',8460,'컵 누들 10개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (28,'ELECTRONICS','cleaning-machine.png',198000,'청소기');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (29,'BEAUTY','brush-makeup.png',27500,'브러쉬 메이크업 1세트');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (30,'BEAUTY','oleo-cream.png',15500,'염모제 2개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (31,'FOODS','carrot.png',13390,'당근 3kg 1개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (32,'KITCHEN','coffee-machine.png',89000,'커피머신');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (33,'BATHROOM','razor.png',13900,'일회용 면도기 50개입');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (34,'FOODS','cabbage.png',17010,'양상추 5개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (35,'ELECTRONICS','macmini.png',792020,'맥미니');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (36,'FASHION','socks.png',15900,'양말 12켤레');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (37,'BEAUTY','nail-nipper.png',35000,'손톱 깎이');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (38,'FOODS','chocolate.png',28280,'초콜렛 16개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (39,'KITCHEN','kitchen-paper.png',17700,'키친타올 100개입 9개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (40,'FASHION','backpack.png',27570,'가방');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (41,'FOODS','cereal1.png',4900,'첵스');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (42,'ELECTRONICS','macbookair.png',1264000,'맥북에어');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (43,'BATHROOM','shampoo.png',25360,'샴푸 2개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (44,'BEAUTY','sun-cream.png',21400,'선크림 1개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (45,'FOODS','snack1.png',67500,'먹태깡 16개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (46,'KITCHEN','plate.png',5560,'접시 1그릇');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (47,'ELECTRONICS','desktop.png',174000,'사무용 데스크탑');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (48,'FOODS','pringles.png',18900,'프링글스 양파맛 12개');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (49,'ELECTRONICS','camera.png',199000,'카메라');
INSERT INTO `products` (`id`,`category`,`image`,`price`,`title`) VALUES (50,'BATHROOM','hanger.png',16840,'접이식 행거');
